apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Make sure this matches the labels in your Deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Assuming your Nginx is serving on port 80
      nodePort: 31000  # Choose a nodePort within the allowed range (e.g., 30000-32767)
