apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: redheaven/my-nginx-image
  name: argocd-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:irfanrizkiantopratama/argocd-test.git
    targetRevision: HEAD
    path: k8s/nginx
  destination: 
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
