apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-nginx
  namespace: my-app
spec:
  project: default

  source:
    repoURL: git@github.com:irfanrizkiantopratama/argocd-test.git
    targetRevision: HEAD
    path: k8s/nginx
  destination: 
    server: https://kubernetes.default.svc
    namespace: my-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true